name: Update Directory Structure
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: APIKEY        
        run: |
          echo $APIKEY
          echo $GIT_NAME
